on:
  pull_request:
  push:
    branches:
      - main
      - dev

name: continuous-integration

jobs:
  test:
    runs-on: ubuntu-latest
    name: Nushell formatter test
    steps:
      - uses: actions/checkout@v4
      - uses: hustcer/setup-nu@main
        with:
          version: "*"
      - run: nu --version
      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.13.0
      - name: Cargo binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Install topiary-cli
        run: |
          topiary --version || cargo binstall --no-confirm topiary-cli
      - name: Run tests
        run: nu run_test.nu
